version: "3.8"
services:
  preprocessor:
    build:
      context: ./container1
    volumes:
      - ./shared_memory:/shared_memory
    restart: "no"  # No reiniciar el contenedor
    entrypoint: sh -c "mkdir -p /shared_memory && /app/LCG"

  processor:
    build:
      context: ./container2
    volumes:
      - ./shared_memory:/shared_memory
    depends_on:
      - preprocessor
    restart: "no"  # No reiniciar el contenedor
    entrypoint: sh -c "sh /app/watcher.sh"

volumes:
  shared_memory:
    driver: local
